services:
  app:
    image: 'template-generator:latest'
    container_name: app
    ports:
      - "3662:3662"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/template-generator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=template-generator'
      - 'POSTGRES_PASSWORD=postgres@123'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    