name: Template Generator CI & CD

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'releases/**'
      - 'features/**'
  workflow_dispatch:

jobs:
  test:
    name: Test - Units
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Test with Maven
      run: mvn compile test

  build:
    name: Build, Publish & Docker push
    if: ${{github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'releases/release')}}
    runs-on: ubuntu-latest
    needs: [test, sonar]
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_USERNAME }}/template-generator:${{ github.run_number }}